on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i
      - name: serverless deploy
        uses: serverless/github-action@v3
        with:
          args: serverless deploy --BASE_ENDPOINT_URL=${{secrets.BASE_ENDPOINT_URL}} --AUTH_PASSWORD=${{secrets.AUTH_PASSWORD}} --AUTH_USER=${{secrets.AUTH_USER}} --verbose
        env:
          #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
