name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stages:
          - stage: "dev"
            AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_DEV"
            AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_DEV"
          - stage: "prod"
            AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_PROD"
            AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_PROD"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: serverless/github-action@v3
        with:
          args: -c "serverless deploy --stage=${{ matrix.stages.stage }} --BASE_ENDPOINT_URL=${{secrets.BASE_ENDPOINT_URL}} --AUTH_PASSWORD=${{secrets.AUTH_PASSWORD}} --AUTH_USER=${{secrets.AUTH_USER}} --verbose"
          entrypoint: /bin/bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[matrix.stages.AWS_ACCESS_KEY_ID] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.stages.AWS_SECRET_ACCESS_KEY] }}
          SLS_DEBUG: 1
